// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class AppStng
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Note { get; set; }

    public int LesnTyp { get; set; }

    public string SubLesnId { get; set; }

    public string UserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public bool ProLtgl { get; set; }

    public bool Audible { get; set; }
}