// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class GuestbookMsg
{
    public int Id { get; set; }

    public string EventData { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Message { get; set; }
}