// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class LkuLevel
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Desc { get; set; }

    public virtual ICollection<Problem> Problems { get; set; } = new List<Problem>();
}