// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using OneBase.Db.PowerTools.Models;

namespace OneBase.Db.PowerTools.Models
{
    public partial class OneBaseContext
    {

        [DbFunction("DateOnly", "dbo")]
        public static DateOnly? DateOnly(DateTime? InputDateTime)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_diagramobjects", "dbo")]
        public static int? fn_diagramobjects()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<int?> fn_diagramobjectsAsync()
            => await Database.SqlQueryRaw<int?>("select Value = [dbo].[fn_diagramobjects]()").SingleAsync();

        [DbFunction("KnownUserName", "APi")]
        public static string KnownUserName(string hash)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
