// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class Player
{
    public string Id { get; set; }

    public string FullName { get; set; }

    public string Password { get; set; }

    public string Desc { get; set; }

    public DateTime AddedAt { get; set; }

    public string AddedBy { get; set; }

    public DateTime? DeletedAt { get; set; }

    public string DeletedBy { get; set; }

    public virtual ICollection<Audition> Auditions { get; set; } = new List<Audition>();

    public virtual ICollection<TombStone> TombStones { get; set; } = new List<TombStone>();
}