// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class Problem
{
    public int Id { get; set; }

    public string ProblemText { get; set; }

    public string SolutionText { get; set; }

    public string HintMessage { get; set; }

    public string BatchSource { get; set; }

    public string Notes { get; set; }

    public int Grade { get; set; }

    public DateTime AddedAt { get; set; }

    public string AddedBy { get; set; }

    public DateTime? DeletedAt { get; set; }

    public string DeletedBy { get; set; }

    public int? LevelId { get; set; }

    public int? LanguageId { get; set; }

    public virtual ICollection<Audition> Auditions { get; set; } = new List<Audition>();

    public virtual LkuLanguage Language { get; set; }

    public virtual LkuLevel Level { get; set; }
}