// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneBase.Db.PowerTools.Models;

public partial class SessionResult
{
  public int Id { get; set; }

  public string UserId { get; set; }

  public string ExcerciseName { get; set; }

  public int PokedIn { get; set; }

  public DateTime DoneAt { get; set; }

  public TimeOnly Duration { get; set; }

  public string Note { get; set; }

  public bool? IsRecord { get; set; }

  public int? TotalRunCount { get; set; }

  public virtual User User { get; set; }


  [NotMapped] public int CpM { get { return (int)(Duration.ToTimeSpan().TotalMinutes == 0 ? 0d : PokedIn / Duration.ToTimeSpan().TotalMinutes); } }
}