// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class TombStone
{
    public string Id { get; set; }

    public string User { get; set; }

    public string PlayerId { get; set; }

    public virtual Player Player { get; set; }
}