// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class User
{
    public string UserId { get; set; }

    public string FullName { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual ICollection<SessionResult> SessionResults { get; set; } = new List<SessionResult>();
}