// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class VwEventUserUtc
{
    public DateTime DoneAt { get; set; }

    public string Nickname { get; set; }

    public string EventName { get; set; }
}