// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class VwUser
{
    public DateTime? CreatedAt { get; set; }

    public DateTime? LastEvEst { get; set; }

    public int? Cnt { get; set; }

    public string Nickname { get; set; }

    public string EventData { get; set; }
}