// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class VwUserHopsUtc
{
    public int Id { get; set; }

    public string Nickname { get; set; }

    public int? Hops { get; set; }

    public DateTime Started { get; set; }

    public DateTime? Finished { get; set; }

    public int? TotalMin { get; set; }

    public DateTime? ReviewedAt { get; set; }
}