// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class WebEventLog
{
    public int Id { get; set; }

    public int WebsiteUserId { get; set; }

    public string EventName { get; set; }

    public DateTime DoneAt { get; set; }

    public virtual WebsiteUser WebsiteUser { get; set; }
}