// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OneBase.Db.PowerTools.Models;

public partial class WebsiteUser
{
    public int Id { get; set; }

    public string EventData { get; set; }

    public string Nickname { get; set; }

    public string Note { get; set; }

    public bool? DoNotLog { get; set; }

    public int? ReviewedBy { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public DateTime LastVisitAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<WebEventLog> WebEventLogs { get; set; } = new List<WebEventLog>();
}